name: NormandyLogin
version: '1.0'
main: io.wdsj.normandy.NormandyLogin
api-version: '1.21'
authors:
  - HeyWTF_IS_That
  - HaHaWTH
  - 0D00_0721
folia-supported: true
softdepend:
  - AuthMe
commands:
  generatetoken:
    description: Generate an access token
    aliases: [gentoken]
permissions:
  normandylogin.command.gentoken:
    description: Allows the player to generate a access token
    default: true
