name: NormandyLogin
version: '1.0'
main: io.wdsj.normandy.NormandyLogin
api-version: '1.21'
authors:
  - HaHaWTH
folia-supported: true
softdepend:
  - AuthMe
commands:
  generatetoken:
    description: Generate an access token
    aliases: [gentoken]
  revoketoken:
    description: Revoke an access token
    aliases: [deltoken, revoke, removetoken]
permissions:
  normandylogin.command.gentoken:
    description: Allows the player to generate a access token
    default: true
  normandylogin.command.revoketoken.self:
    description: Allows the player to revoke a access token
    default: true
  normandylogin.command.revoketoken.others:
    description: Allows the player to revoke a access token of others
    default: op
